site_name: PineSAM documentation
repo_name: PineSAM
site_description: "PineSAM is a Bluetooth BLE app to control the Pinecil V2 through a browser."
site_url: 'https://builder555.github.io/PineSAM'
repo_url: https://github.com/builder555/PineSAM
edit_uri: edit/dev/docs

theme:
    name: material
    custom_dir: docs/assets/overrides
    favicon: assets/img/favicon.ico
    logo: assets/img/logo.png
    icon:
      repo: fontawesome/brands/github
      edit: material/file-edit-outline
    language: 'en'
    font: false
    features:
      - navigation.top
      - navigation.instant
      - navigation.sections
      #- navigation.indexes
      #- navigation.expand
      - toc.follow
      - search.suggest
      - search.highlight
      - search.share
      - content.code.copy
      - navigation.footer
      - content.action.edit
      - content.action.view
      - toc.integrate


nav:
    - ğŸ‘‹ Welcome!: index.md
    - ğŸš€ Getting started:
        - ğŸ–¥ï¸ Installation: getting-started/installation.md
        - ğŸš§ Known issues: getting-started/known-issues.md
    - ğŸ“œ Usage:
        - ğŸ—ƒï¸ How to use: how-to-use/index.md
        - âš™ï¸ Settings Categories: how-to-use/settings.md
        - ğŸ“’ Debugging & Terminal: how-to-use/debugging & terminal.md

theme: 

# For Privacy - defines/uses local fonts
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/fonts.css


extra_javascripts:
  - assets/javascripts/extra.js

# Plugins
plugins:
  - autolinks
  - search
  - git-committers:
      repository: neil-forks/PineSAM-river
      branch: NeilHanlon-patch-1
  - git-revision-date-localized:
      type: date
  - git-authors:
      show_contribution: true
      show_line_count: true
      show_email_address: false
      count_empty_lines: true
      fallback_to_empty: true
      sort_authors_by: contribution
      authorship_threshold_percent: 0
      enabled: true



  - awesome-pages:
        collapse_single_pages: true
  - i18n:
      default_language: en
      languages:
          en: English
          de: Deutsch
          fr: FranÃ§ais
          es: EspaÃ±ol
          it: Italian
          ja: æ—¥æœ¬èª
          zh: ç®€ä½“ä¸­æ–‡
          sv: Svenska
          pl: Polish
          pt: PortuguÃªs
          ru: Russian
  - git-revision-date-localized:
      type: date

extra:
  alternate:
    - name: Default (en)
      link: ./
      lang: en
    - name: English
      link: ./en/
      lang: en
    - name: FranÃ§ais
      link: ./fr/
      lang: fr
    - name: Deutsch
      link: ./de/
      lang: de
    - name: EspaÃ±ol
      link: ./es/
      lang: es
    - name: Italian
      link: ./it/
      lang: it
    - name: æ—¥æœ¬èª
      link: ./ja/
      lang: ja
    - name: Polish
      link: ./pl/
      lang: pl
    - name: PortuguÃªs
      link: ./pt/
      lang: pt
    - name: ç®€ä½“ä¸­æ–‡
      link: ./zh/
      lang: zh
    - name: Svenska
      link: ./sv/
      lang: sv
    - name: Russian
      link: ./ru/
      lang: ru




# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - admonition
  - toc:
      permalink: "ğŸ”—&#xFE0E;"
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.tasklist
  - footnotes
  - def_list
  - meta